# Generated by Django 4.2.7 on 2025-10-27 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('residencial', 'Servicios Residenciales'), ('empresarial', 'Servicios Empresariales'), ('especializado', 'Servicios Especializados'), ('postobra', 'Servicios Post-obra')], max_length=20, verbose_name='Tipo de Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Servicio')),
                ('direccion_servicio', models.TextField(verbose_name='Dirección del Servicio')),
                ('fecha_servicio', models.DateTimeField(verbose_name='Fecha y Hora del Servicio')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Estimado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Servicio Agendado',
                'verbose_name_plural': 'Servicios Agendados',
                'db_table': 'servicios_agendados',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
