# Generated by Django 4.2.7 on 2025-10-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_asignado', models.CharField(max_length=100, verbose_name='Equipo Asignado')),
                ('progreso_porcentaje', models.IntegerField(default=0, verbose_name='Progreso (%)')),
                ('tareas_completadas', models.JSONField(default=list, verbose_name='Tareas Completadas')),
                ('ubicacion_actual', models.CharField(blank=True, max_length=200, verbose_name='Ubicación Actual del Equipo')),
                ('tiempo_estimado_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Estimado de Finalización')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicioagendado', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Seguimiento de Servicio',
                'verbose_name_plural': 'Seguimientos de Servicios',
                'db_table': 'seguimiento_servicios',
            },
        ),
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateTimeField(verbose_name='Fecha de Finalización')),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calificación (1-5)')),
                ('comentarios_cliente', models.TextField(blank=True, verbose_name='Comentarios del Cliente')),
                ('reporte_trabajo', models.TextField(blank=True, verbose_name='Reporte de Trabajo Realizado')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicioagendado', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Historial de Servicio',
                'verbose_name_plural': 'Historiales de Servicios',
                'db_table': 'historial_servicios',
            },
        ),
        migrations.CreateModel(
            name='FacturacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('vencido', 'Vencido')], default='pendiente', max_length=15, verbose_name='Estado del Pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Método de Pago')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Número de Factura')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicioagendado', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Facturación de Servicio',
                'verbose_name_plural': 'Facturaciones de Servicios',
                'db_table': 'facturacion_servicios',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
